query getAllProjects($status: [String]) {
  projects(filter: { status: { _in: $status } }) {
    id
    sort
    title
    description
    type
    image {
      id
      title
      width
      height
    }
    links
    labels {
      label {
        name
      }
    }
    translations {
      language {
        code
      }
      description
    }
  }
}
