query getAllExperience {
  experiences(sort: "-startDate") {
    id
    position
    description
    company
    companyUrl
    startDate
    endDate
    city
    image {
      id
      title
    }
    labels {
      label {
        name
      }
    }
    translations {
      language {
        code
      }
      position
      description
      city
    }
  }
}
