query getAllExperience($status: [String]) {
  experiences(filter: { status: { _in: $status } }, sort: "-startDate") {
    id
    sort
    position
    description
    company
    companyUrl
    startDate
    endDate
    city
    image {
      id
      title
    }
    labels {
      label {
        name
      }
    }
    translations {
      language {
        code
      }
      position
      description
      city
    }
  }
}
