query getAllProjects {
  projects {
    id
    title
    description
    type
    image {
      id
      title
      width
      height
    }
    links
    labels {
      label {
        name
      }
    }
    translations {
      language {
        code
      }
      description
    }
  }
}
