query getAllEducation {
  educations(sort: "-startDate") {
    id
    title
    description
    place
    startDate
    endDate
    city
    image {
      id
      title
    }
    translations {
      language {
        code
      }
      title
      description
      city
    }
  }
}
